### ISSUE TITLE
Crash in irc disconnect

### ISSUE THREAD

**Issue by ChillerDragon** [discord-irc/irc-websockets#10]
backend logs
```
[*][ddnet][developer] <ChillerDragon> mr international lerato
[*][ddnet][developer] <ChillerDragon> ü
[*][ddnet][developer] <ChillerDragon> i am used to "c" i had it for years
/home/chiller/git/irc-websockets/node_modules/irc/lib/irc.js:936
    if (!this.conn.requestedDisconnect) {
                   ^

TypeError: Cannot read properties of null (reading 'requestedDisconnect')
    at Client.send (/home/chiller/git/irc-websockets/node_modules/irc/lib/irc.js:936:20)
    at /home/chiller/git/irc-websockets/node_modules/irc/lib/irc.js:1076:22
    at Array.forEach (<anonymous>)
    at /home/chiller/git/irc-websockets/node_modules/irc/lib/irc.js:1075:25
    at Array.forEach (<anonymous>)
    at Client._speak (/home/chiller/git/irc-websockets/node_modules/irc/lib/irc.js:1073:12)
    at Client.say (/home/chiller/git/irc-websockets/node_modules/irc/lib/irc.js:1060:10)
    at sendIrc (/home/chiller/git/irc-websockets/dist/irc.js:50:12)
    at onMessage (/home/chiller/git/irc-websockets/dist/features/messages.js:69:28)
    at Socket.<anonymous> (/home/chiller/git/irc-websockets/dist/index.js:109:34)

Node.js v18.17.1
```

independent irc client weechat logs
```
14:32:13 +ws-client | <ChillerDragon> mr international lerato
14:32:15 +ws-client | <ChillerDragon> ü
14:32:48        <-- | ws-client (~nodebot@2a01:4f8:141:51ca:400::15) has quit (EOF from client)
14:35:42        <-- | scrumplex (~quassel@dynamic-002-243-091-235.2.243.pool.telefonica.de) has quit (Ping timeout)
14:38:20        <-- | heinrich5991 (~hein5991@hein5991.users.quakenet.org) has quit (*.net *.split)
14:38:20        <-- | bridge (~bridge@heinrich5991.de) has quit (*.net *.split)
14:38:20        <-- | ochristi (~ochristi@ochristi.users.quakenet.org) has quit (*.net *.split)
14:38:20        <-- | b3z (~b3z@vmd41962.contaboserver.net) has quit (*.net *.split)
14:44:57        --> | ochristi (~ochristi@ochristi.users.quakenet.org) has joined #ddnet 
14:44:57        --> | bridge (~bridge@heinrich5991.de) has joined #ddnet
14:44:57        --> | b3z (~b3z@vmd41962.contaboserver.net) has joined #ddnet
14:44:57        --> | heinrich5991 (~hein5991@hein5991.users.quakenet.org) has joined #ddnet
14:44:57         -- | Mode #ddnet [+ovv heinrich5991 b3z bridge] by *.quakenet.org
14:46:07    +bridge | <Ewan> qwfpgjluyarstdhneiozxcvbkm
14:46:43    +bridge | <Ewan> think about it
```

**Comment by ChillerDragon** [comment]
```
[*] popping message from queue (3 left)
[*] popping message from queue (2 left)
/home/chiller/git/irc-websockets/node_modules/irc/lib/irc.js:936
    if (!this.conn.requestedDisconnect) {
                   ^

TypeError: Cannot read properties of null (reading 'requestedDisconnect')
    at Client.send (/home/chiller/git/irc-websockets/node_modules/irc/lib/irc.js:936:20)
    at /home/chiller/git/irc-websockets/node_modules/irc/lib/irc.js:1076:22
    at Array.forEach (<anonymous>)
    at /home/chiller/git/irc-websockets/node_modules/irc/lib/irc.js:1075:25
    at Array.forEach (<anonymous>)
    at Client._speak (/home/chiller/git/irc-websockets/node_modules/irc/lib/irc.js:1073:12)
    at Client.say (/home/chiller/git/irc-websockets/node_modules/irc/lib/irc.js:1060:10)
    at sendIrc (/home/chiller/git/irc-websockets/dist/irc.js:50:12)
    at Timeout.popQueueEntry [as _onTimeout] (/home/chiller/git/irc-websockets/dist/features/webhooks.js:57:28)
    at listOnTimeout (node:internal/timers:569:17)

Node.js v18.17.1
```
